[package]
name = "rqrr_ex_nif"
version = "0.1.2"
authors = []
edition = "2018"

[lib]
name = "rqrr_ex_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.27"
image = "0.24"
rqrr = "0.6.0"
